name: Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pull_request:
    if: github.event_name == 'pull_request'
    runs-on: macos-latest
    steps:
      - run: echo "This runs on pull requests"
  push:
    if: github.event_name == 'push'
    runs-on: macos-latest
    steps:
      - run: echo "Thiss runs on pushes"
